-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    username character varying NOT NULL,
    password character varying NOT NULL,
    salt character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.games
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying NOT NULL,
    description text NOT NULL,
    game_admin_id integer NOT NULL,
    max_team_size integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.checkpoints
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying NOT NULL,
    description text NOT NULL,
    qr_code_path character varying NOT NULL,
    game_id integer,
    previous integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.comments
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    comment text NOT NULL,
    author_id integer NOT NULL,
    checkpoint_id integer NOT NULL,
    date_time timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.team
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    game_id integer NOT NULL,
    name character varying NOT NULL,
    points integer NOT NULL,
    game_times time without time zone[] NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.team_members
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    user_id integer,
    team_id integer
);

CREATE TABLE IF NOT EXISTS public.unlocked
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    checkpoint_id integer,
    team_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.achivements
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    description text NOT NULL,
    game_id integer NOT NULL,
    unlocked boolean NOT NULL,
    bonus integer NOT NULL,
    treshold integer,
    checkpoint_id integer,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.games
    ADD CONSTRAINT game_admin_id FOREIGN KEY (game_admin_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.checkpoints
    ADD CONSTRAINT game FOREIGN KEY (game_id)
    REFERENCES public.games (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.checkpoints
    ADD CONSTRAINT previous FOREIGN KEY (previous)
    REFERENCES public.checkpoints (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT author FOREIGN KEY (author_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comments
    ADD CONSTRAINT checkpoint FOREIGN KEY (checkpoint_id)
    REFERENCES public.checkpoints (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.team
    ADD CONSTRAINT game FOREIGN KEY (game_id)
    REFERENCES public.games (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT "user" FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.team_members
    ADD CONSTRAINT team FOREIGN KEY (team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.unlocked
    ADD CONSTRAINT team FOREIGN KEY (team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.unlocked
    ADD CONSTRAINT checkpoint FOREIGN KEY (checkpoint_id)
    REFERENCES public.checkpoints (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.achivements
    ADD CONSTRAINT game FOREIGN KEY (game_id)
    REFERENCES public.games (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.achivements
    ADD CONSTRAINT checkpoint FOREIGN KEY (checkpoint_id)
    REFERENCES public.checkpoints (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;