FROM  python:3.11

WORKDIR /app/backend
COPY ./backend/requirements.txt /app/backend/requirements.txt
RUN pip3 install --no-cache-dir -r /app/backend/requirements.txt
COPY ./backend/ .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
